version: '3.4'

services:
  dockerdemoapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  dockerdemo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

